version: '2'
services:
  application:
    name: project-${PROJECT_NAME}
    label: project-${PROJECT_NAME}
    build:
      context: ../dockerfile
      args:
        project_name: ${PROJECT_NAME}
        application_file: ${APPLICATION_FILE}
    networks:
      - ${PROJECT_NAME}
