version: '2'

services:
  proxy:
    image: traefik
    label: pallur:system
    command: --web --docker --docker.domain=docker.localhost --logLevel=DEBUG
    networks:
      - webgateway
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - pallur/resources/compose/configuration/traefik.toml:/traefik.toml
  etcd:
    image: quay.io/coreos/etcd
    label: pallur:system
    restart: always
    ports:
        - 2379:2379
        - 2380:2380
    environment:
        ETCD_NAME: pallur

networks:
  webgateway:
    driver: bridge
