version: '2'

services:
  gogs:
    image: gogs
    name: project-${PROJECT_NAME}
    label: project-${PROJECT_NAME}
    networks:
      - ${PROJECT_NAME}


networks:
  ${PROJECT_NAME}:
    driver: bridge
