version: '2'
services:
  application:
    container_name: project-${PROJECT_NAME}
    #labels:
    #  - com.pallur.project=${PROJECT_NAME}
    build:
      context: ../dockerfile
    environment:
      - "project_name=${PROJECT_NAME}"
      - "application_file=${APPLICATION_FILE}"
    networks:
      - ${PROJECT_NAME}
    ports:
      - "8081:80"
networks:
  HelloWorld:
    external: true
