defaultEntryPoints = ["http", "https"]

[web]
address = ":8080"
  [web.auth.basic]
  users = ["admin:$apr1$Rc23KWRU$.K8ZwCp.ekuZUOaBvrjqJ/"]

[entryPoints]
  [entryPoints.http]
  address = ":80"
  [entryPoints.https]
  address = ":443"
    [entryPoints.https.tls]

[acme]
email = "alicia@aliciasteen.com"
storage = "acme.json"
entryPoint = "https"
  [acme.httpChallenge]
  entryPoint = "http"
onHostRule = true
onDemand = true


[[acme.domains]]
  main = "server.pallur.cloud"
