#!bin/bash -e

# Create new project

unset $PROJECT_NAME
unset $PROJECT_ROUTE
unset $PROJECT_REPOSITORY

SUBCOMMAND_NAME="create"

cmd_desc() {
  printf "Create new project"
}

help() {
  echo "usage: ${CMD} ${SUBCOMMAND_NAME} <options>"
  echo ""
  echo "create [OPTION]";
  echo ""
  echo "Options:";
  echo "    -n    Name of Project. Required.";
  echo "    -c    URL of Application Repository. Required.";
  echo "    -r    Route for the project. Required.";
  echo "    -h    Print this help"
  exit 1;
}

project_create() {
  echo "done"
}

shift $(($OPTIND -1))

while getopts "n:r:c:h" OPTION; do
  case $OPTION in
    n)
      PROJECT_NAME=$OPTARG
      ;;
    r)
      PROJECT_ROUTE=$OPTARG
      ;;
    c)
      PROJECT_REPOSITORY=$OPTARG
      ;;
    h|-help)
      help
      exit 1
      ;;
    *)
      echo "Invalid parameter(s) or option(s)."
      help
      exit 1
      ;;
  esac
done

if [ $# -lt 1 ]; then
  help
  exit 0
fi

if [ ! -z "$PROJECT_NAME" ] && [ ! -z "$PROJECT_ROUTE" ] && [ ! -z "$PROJECT_ROUTE" ]; then
  project_create
else
  echo "Provide all options"
  help
fi
