#!bin/bash -e

# Bring project up

SUBCOMMAND_NAME="up"

unset PROJECT_NAME
unset APPLICATION_FILE

cmd_desc() {
  echo "Deploy project application"
}

help() {
  echo "usage: ${CMD} ${SUBCOMMAND_NAME} <options>"
  cmd_desc
  echo ""
  echo "create [OPTION]";
  echo ""
  echo "Options:";
  echo "    -n    Name of Project. Required.";
  echo "    -f    Main python file name. Required.";
  echo "    -h    Print this help"
  exit 1;
}

application_up() {
  echo "Deploying application..."
  if ! docker network create ${PROJECT_NAME} &> /dev/null; then
       echo "Network already exists: ${PROJECT_NAME}"
   else
       echo "Created Docker network: ${PROJECT_NAME}"
   fi
  docker-compose -p ${PROJECT_NAME} -f /pallur/resources/compose/docker-compose-application.yml up --build -d
}

shift $(($OPTIND -1))

while getopts "n:f:h" OPTION; do
  case $OPTION in
    n)
      export PROJECT_NAME=$OPTARG
      ;;
    f)
      export APPLICATION_FILE=$OPTARG
      ;;
    h|help)
      help
      exit 1
      ;;
    *)
      echo "Invalid parameter(s) or option(s)."
      help
      exit 1
      ;;
  esac
done

if [ $# -lt 1 ]; then
  help
  exit 0
fi

if [ ! -z "$PROJECT_NAME" ] && [ ! -z "$APPLICATION_FILE" ]; then
  application_up
fi
